spring:
  application:
    name: xmlservlet
server:
  servlet:
    context-path: /${spring.application.name} 

db:
 driver: org.h2.Driver
 url: jdbc:h2:mem:inMemoryDB
 username: sa
 password: 
 
hibernate:
  dialect: org.hibernate.dialect.H2Dialect
  format_sql: true
  hbm2ddl:
    auto: create-drop
  ejb:
    naming_strategy: org.hibernate.cfg.ImprovedNamingStrategy
  show_sql: false

logging:
  config: classpath:log4j2.xml
  
#logging:
#  level:
#    com.components.xmlservlet: INFO
#  pattern:
#    console: "%d{HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n"
    
---
spring:
  profiles: test
  application:
    description: test profile
    
db:
 driver: org.h2.Driver
 url: jdbc:h2:mem:test
 username: sa
 password:        